apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::803740960078:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J5GY4TGKLY8N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::803740960078:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-05T15:54:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "221101"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cb301b6a-6c1b-412f-93a9-227de150cde8
